### PR TITLE
:arrow_up: Django 1.9

### PR DESCRIPTION
**Pull request by thraxil**
django-haystack 2.4.1 appears to work with Django 1.9, so that's no
longer the blocker.

Some things I did run into:

* had to fork the now unmaintained django-googlecharts
* django-databrowse 2014.9.26 breaks under 1.9, but the older 1.2
  version seems to work fine with 1.9, so I dropped it back to that
  until a newer version comes out
* template_utls doesn't work with 1.9. AFAICT, it was being imported and
  added to INSTALLED_APPS, but never actually used, so I just removed it.

### CODE REVIEW

**Comment by sdreher** [comment]
* django-databrowse has [1.9 incompatibilities](https://github.com/Alir3z4/django-databrowse/blob/1.2/django_databrowse/sites.py#L167). django.db.models.get_model was fully deprecated in 1.9. The error surfaced when reviewing an object page (/portal/browse/portal/learningactivity/objects/12/).

* migrate is throwing an error in my local env. (master works properly)
```
./manage.py migrate  
django.db.utils.OperationalError: could not open extension control file "/Library/PostgreSQL/9.2/share/postgresql/extension/postgis.control": No such file or directory

```

* haystack search is throwing an error in my local env, perhaps as a result of the migration issues (master works properly)
```
/portal/search/?q=turtle
'NoneType' object has no attribute '_default_manager'
```

**Comment by sdreher** [comment]
@thraxil - one note on this - factoring out databrowse should be fairly simple for this application. I can take a task to do this. Haystack is obviously a little more problematic.
